site_name: Yast
site_desciption: Yet another startlette as Yast

theme:
  name: 'material'

repo_name: eml/yast
repo_url: https://github.com/emryslou/yast
edit_url: ''

nav:
  - 介绍: 'index.md'
  - MessageHandler: 'message_handler.md'
  - Responses: 'responses.md'
  - Config: 'config.md'
  - Websockets: 'websockets.md'
  - Applications: 'applications.md'
  - Concurrency: 'concurrency.md'
  - Background: 'background.md'
  - Types: 'types.md'
  - Convertors: 'convertors.md'
  - Staticfiles: 'staticfiles.md'
  - Routing: 'routing.md'
  - Testclient: 'testclient.md'
  - Exceptions: 'exceptions.md'
  - Requests: 'requests.md'
  - Endpoints: 'endpoints.md'
  - Formparsers: 'formparsers.md'
  - Status: 'status.md'

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
