site_name: Yast
site_desciption: Yet another startlette as Yast

theme:
  name: 'material'

repo_name: eml/yast
repo_url: https://github.com/emryslou/yast
edit_url: ''

nav:
  - 介绍: 'index.md'
  - TestClient: 'testclient.md'
  - Schemas: 'schemas.md'

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false